### ISSUE TITLE
slideActiveClass on SwipeSlide is not working right

### ISSUE THREAD

**Issue by doxiaodong** [nolimits4web/swiper#4086] opened 2021-01-12 02:49 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: all
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/snowy-breeze-ybclz

### What you did
see codesandbox link

### Expected Behavior
custom `slideActiveClass` on active slide

### Actual Behavior
custom `slideActiveClass` may be disappeared
![image](https://user-images.githubusercontent.com/6927481/104262904-7f896a00-54c3-11eb-9d20-8b654d83011b.png)

BTW, when I remove props.swiper on SwipeSlide , it works right. Maybe updating classes by swiper is not right

**Comment by vltansky** [comment] 2021-01-22 09:34
related #4020

**Comment by vltansky** [comment] 2021-01-25 13:23
@doxiaodong as a workaround you can use  `isActive` variable to set class or whatever you need
```
<Swiper>
  <SwiperSlide>
    {({ isActive }) => (
      <div>Current slide is {isActive ? 'active' : 'not active'}</div>
    )}
  </SwiperSlide>
</Swiper>
```
https://swiperjs.com/react#swiper-slide-render-function

**Comment by nolimits4web** [comment] 2021-01-25 16:32
Sorry, closing this as this is by design. Those namespace class names are designed only to be used with Core version, and not supported by React/Vue/Svelte/Angular components. If you need custom class on slides, just add one in addition to `swiper-class`.

**Closed by nolimits4web** 2021-01-25 16:32 UTC
Labels: Angular, React, Svelte, Vue, bug confirmed, has demo
