### ISSUE TITLE
Swiper transitions is flickering in safari

### ISSUE THREAD

**Issue by bariskrdrl** [nolimits4web/swiper#3558] opened 2020-05-01 16:53 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.8
* Platform/Target and Browser Versions: macOS, SAFARI
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/200-infinite-loop.html

### What you did
I just added a swiper and pressed the forward button quickly

### Expected Behavior
To ensure that it passes without shaking

### Actual Behavior
I looked at swiperjs.com to make sure that it wasn't spoiling something and I saw that trembling again.
This problem seems to have been closed before but there is still this error.

**Comment by tiadaguru** [comment] 2020-05-10 21:48
Agreed. We've discussed this relatively extensively in still-open #3527 , but no replies nor updates. Perhaps these two open issues can be merged?

This bug is absolutely reproducible on even swiperjs.com's demos, so I hope it gets looked it.

**Comment by nolimits4web** [comment] 2020-05-11 14:47
Duplicate of #3527

**Closed by nolimits4web** 2020-05-11 14:47 UTC
