### ISSUE TITLE
v.wrapper.transition is not a function

### ISSUE THREAD

**Issue by iamhd** [nolimits4web/Swiper#1410] opened 2015-08-25 13:07 UTC
Still it is not fixed on version 3.1.2

**Comment by iamhd** [comment] 2015-08-25 13:15
But It is not happening when using non jquery version.
Please try to fix this issue and your slider will rocks.

**Comment by nolimits4web** [comment] 2015-08-25 13:28
The issue is not in Slider. Please provide at least live example or JSFiddle with this issue

**Comment by nolimits4web** [comment] 2015-09-28 19:32
Closing as no further response/discussion

**Closed by nolimits4web** 2015-09-28 19:32 UTC
