### ISSUE TITLE
Navigation in loop mode wait translation to finish before start new one

### ISSUE THREAD

**Issue by gfnool** [nolimits4web/Swiper#1221] opened 2015-04-04 09:05 UTC
Hi,

When the slider has loop option set to true and you click fast on the navigate button, the swiper waits every step to be finished before allow another click on the pagination. It wait the animation to be finished.
You can see it in the demo:
http://www.idangero.us/swiper/demos/15-infinite-loop.html

What I would like to have is a behaviuor like the normal mode:
http://www.idangero.us/swiper/demos/14-nav-arrows.html

Is there a possibile workaround to fix it or, better, could be this filed under "bug" and fixed?

Thank you.

EDIT:

it seems that is affected by this line in slideNext method:
if (s.params.loop) {  if (s.animating) return false; ......

What kind of problem I could face if I comment that?
My project is based on a swiper with only one slide per view. Do you think I will have any problems?
Thank you.

**Comment by nolimits4web** [comment] 2015-04-04 13:55
Hi, that is because loop need to be "fixed"/shifted, which is impossible during transition. You may look at the fixLoop function inside and what it does

**Comment by gfnool** [comment] 2015-04-05 08:00
I've looked at the fixLoop function and I understanded what it does, but still I'm finding no bug using the slider without that check (if (s.animating) return false).

I also tried a swiper with more slides per view without seeing any error in the movements.

What am I missing?
I would like to use it without the check for performance reasons but I would love to see where the problem is. Thank you for your support if you can help me understand this thing.

**Comment by nolimits4web** [comment] 2015-04-26 18:32
Closing, as it is currently by design. Without this check, in some browsers, fixLoop may work not correctly

**Closed by nolimits4web** 2015-04-26 18:32 UTC
