### ISSUE TITLE
Swiper v9 Grid Loop ...

### ISSUE THREAD

**Issue by tevfiksirin** [nolimits4web/swiper#6351] opened 2023-02-06 15:17 UTC
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/5882#issuecomment-1411926673_
 
Hello,

First of all, thank you so much for everything.

I leave an example link for this issue,
When the loop is activated, it does not work as it should.

[codesandbox](https://codesandbox.io/p/sandbox/swiper-grid-forked-9u6squ?file=%2Findex.html&selection=%5B%7B%22endColumn%22%3A46%2C%22endLineNumber%22%3A55%2C%22startColumn%22%3A46%2C%22startLineNumber%22%3A55%7D%5D)

Kind regards

**Comment by jomotion11** [comment] 2023-02-06 17:48
The same thing happened to me, loop: true didn't work. I fixed it by installing an older version `8.4.5` and the loop is working for me now.

**Comment by ondrejruzicka** [comment] 2023-02-07 11:51
Loop stopped working for me as well in new `9.0.3` version. 
Not even using grid view. For linear slider there is issue when `slidesPerView` is greater than half of total slides:
https://codepen.io/ondrejruzicka/pen/YzjMaJy (works when you set `slidesPerView` to `4`).

I moved to new version because reworked loop functionality works well with scrollbar. Which is great!

**Comment by jimchampagne** [comment] 2023-02-07 12:46
Same here, after updating to Swiper `9.0.3` loop is broken in some of my projects. 
I read the docs and found some info here -> [https://swiperjs.com/migration-guide-v9](url)

Which contains the following information:
"Loop mode has been fully reworked in version 9 and now instead of duplicating slides, it rearrange current ones dynamically. It comes with new limitation. Amount of slides in loop mode should be at least 2x of slidesPerView value."

So this is where some of my sliders break if they don't have double the slides of the slidesPerView value...

This new v9 version fixed some hydration errors in Nuxt3 but then breaks another thing and adds this limitation.

I do not understand why you would add a limitation like this and not give developers another option?

Hoping for a fix, currently going back to `8.4.7`

Kind regards

**Comment by huyanyou** [comment] 2023-02-08 09:41
Both activeIndex and realIndex are incorrect in loop mode

**Comment by nanna-dk** [comment] 2023-02-08 11:34
Yup, I can confirm this bug.
Thanks for a great project!

**Comment by DannyKr43mer** [comment] 2023-02-15 00:06
> Same here, after updating to Swiper `9.0.3` loop is broken in some of my projects. I read the docs and found some info here -> [https://swiperjs.com/migration-guide-v9](url)
> 
> Which contains the following information: "Loop mode has been fully reworked in version 9 and now instead of duplicating slides, it rearrange current ones dynamically. It comes with new limitation. Amount of slides in loop mode should be at least 2x of slidesPerView value."
> 
> So this is where some of my sliders break if they don't have double the slides of the slidesPerView value...
> 
> This new v9 version fixed some hydration errors in Nuxt3 but then breaks another thing and adds this limitation.
> 
> I do not understand why you would add a limitation like this and not give developers another option?
> 
> Hoping for a fix, currently going back to `8.4.7`
> 
> Kind regards

Yep. I do not get the limitation. The use case where you do not have double the amount of the slidesPerView value is encountered very often (for example in in image galleries, product sliders etc.) This makes swiper v9 basically useless in a lot of use cases. I opened an issue, but it was closed with the comment "that is the limitation now".

**Comment by camilo-mujica** [comment] 2023-04-13 22:25
Same error here, that loop error forced me to downgrade to V8

**Comment by smerriman** [comment] 2023-04-17 22:04
Agreed with comments above. This seems to break the whole idea of a looped carousel, meaning downgrading to v8 is the only option. Now if there is a separate issue that has been resolved in version 9, what do we do?

I strongly suggest reverting this change in v9 - looped sliders with less than double the number of slides is an *extremely* common use case.

**Comment by torchsmith** [comment] 2023-06-16 13:59
+1

**Comment by tsharms** [comment] 2023-06-27 14:44
I downgraded to V8 due to the loop error, experiencing the same issue here.

**Comment by arnojong** [comment] 2023-06-27 14:45
Is there any estimation on when this is going to be fixed? Still need to use v8 because of this.

**Comment by foinf** [comment] 2023-08-04 11:26
This isn't a small limitation. This is a deal breaking limitation making the slider useless for MANY use cases. It should have atleast been provided as an option. After wasting an hour thinking that I must have made a stupid mistake I realized that only downgrading is a solution.

**Comment by torchsmith** [comment] 2023-08-04 20:57
![sad](https://i.imgflip.com/1o12mo.jpg?a469464)

**Comment by torchsmith** [comment] 2023-08-10 17:29
Swiper on v10 before fixing their regressions. ta ta

**Comment by sebastian-marinescu** [comment] 2023-09-01 03:22
Okay, after hours of trying everything possible out, I also reverted to v8 - at least I'm not alone :heart:

**Comment by torchsmith** [comment] 2023-09-01 11:04
I honestly don't know how you guys allowed yourselves to continue without fixing this issue... It feels pretty irresponsible for a core feature to be broken this long.

**Comment by jimchampagne** [comment] 2023-09-01 13:59
Yup, tried the Swiper V10 version on a new project and still had to revert back to 8.4.7. Unfortunate

**Comment by nanna-dk** [comment] 2023-09-15 13:48
It's not a bug. It's a feature, apparently...

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2.

Ref: https://swiperjs.com/swiper-api#param-loop

**Comment by smerriman** [comment] 2023-09-15 19:05
The fact the developer did it deliberately - and has been closing countless
threads by users all now experiencing the same problem - doesn't meant it
doesn't need fixing. It just means they're out of touch with why clients
want carousels. I guess they don't build websites themselves.

**Comment by torchsmith** [comment] 2023-09-18 19:20
> It's not a bug. It's a feature, apparently...
> 
> > Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2.
> 
> Ref: https://swiperjs.com/swiper-api#param-loop

Yeah, it's broken, following that note you mentioned it still doesn't work.

**Comment by nolimits4web** [comment] 2023-10-24 12:17
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one

**Closed by nolimits4web** 2023-10-24 12:17 UTC
Labels: bug confirmed
