### ISSUE TITLE
Fade effect disables slidesPerView and slidesPerColumn

### ISSUE THREAD

**Issue by jrefano** [nolimits4web/Swiper#1885] opened 2016-10-17 21:02 UTC
This is a (multiple allowed):
- [x] bug
- Swiper Version: 3.3.1
- Platform/Target and Browser Versions: chrome osx
### What you did

set `slidesPerView: 3, slidesPerColumn: 2, effect: 'fade'`
### Expected Behavior

group of 6 slides should fade out and display next group
### Actual Behavior

grouping is disabled and only one slide is showing at a time, with fade transition

**Comment by cheb60** [comment] 2017-03-08 16:27
I'm having the same issue. Hope it will be fixed soon!

**Comment by nolimits4web** [comment] 2017-11-13 10:33
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2017-11-13 10:33 UTC
