### ISSUE TITLE
White flicker when slides changes (real iPad/iPhone)

### ISSUE THREAD

**Issue by iTonyYo** [nolimits4web/swiper#3587] opened 2020-05-20 10:25 UTC
[Demo](https://qcb6w.csb.app/).

I really want to know what caused it.
A CSS property? Device rendering/memory issues?

@nolimits4web

**Comment by tiadaguru** [comment] 2020-05-21 03:12
I believe this is a duplicate of #3527, unfortunately. :(

**Comment by nolimits4web** [comment] 2020-05-22 13:17
Duplicate of #3527

**Closed by nolimits4web** 2020-05-22 13:17 UTC
