### ISSUE TITLE
Navigation buttons are not working on Chrome

### ISSUE THREAD

**Issue by sohan5005** [nolimits4web/Swiper#1317] opened 2015-06-14 20:24 UTC
Hi, on the latest version, then navigation buttons (next, previous and paginations) seems to be not working in google chrome. The pagination changes the active slide but clicking on them, doesn't take me to the slide i have clicked. Also the next and previous buttons are not working. The issue is also on the main demo site: http://www.idangero.us/swiper
I have tried different browsers. Only google chrome has this problem.
Older versions still work for me. I don't know maybe the problem is only in my side? or anyone else have the same problem?

**Comment by Itrulia** [comment] 2015-06-15 13:48
Can confirm no navigation buttons work (pagination, arrows, thumbnails, etc) on Chrome.

Version 43.0.2357.124 m

**Comment by sohan5005** [comment] 2015-06-15 14:16
I have found something weird. It did not totally work for me last night. But now, only the next and prev buttons are working but the pagination still not working. And this problems are on chrome.

Maybe something wrong with cookie management of this plugin?

**Comment by Itrulia** [comment] 2015-06-15 16:30
Well I just tested it with my laptop running chromium

Version 41.0.2272.76 Built on Ubuntu 14.04, running on elementary OS 0.3 (64-bit)


And everything worked fine.

**Comment by nolimits4web** [comment] 2015-06-17 19:27
Guys, it is known uncovered issue with only Chrome and only for Windows. Closing for now as duplicate of many other issues here (like #1152) and here http://www.idangero.us/swiper/forum/#!/bugs-and-issues:nextbuttonprevbutton-doesn

**Closed by nolimits4web** 2015-06-17 19:27 UTC

**Comment by Itrulia** [comment] 2015-06-19 07:38
Just FYI this also happens on Ubuntu/OSX from time to time (Chrome and Chromium).

**Comment by scofield-ua** [comment] 2015-12-02 15:13
I had same problem, but fixed it by setting `nextButton` and `prevButton` properties.
