### ISSUE TITLE
Slides get stuck at the end when dragging mouse

### ISSUE THREAD

**Issue by ben-styling** [nolimits4web/swiper#3398] opened 2020-01-13 15:11 UTC
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: **5.3.0**
You can see this on Swiper's own demo.
https://swiperjs.com/demos/110-slides-per-view.html

### What you did
Use the mouse to drag slides, when you get to the end the slides get stuck and the next navigation arrow isn't in the disabled state.

### Expected Behavior
To spring back like it does when you try and go back from the first slide.

### Actual Behavior
The slides get stuck and the next navigation arrow isn't in the disabled state.

**Comment by Raisenku** [comment] 2020-01-15 11:19
Can confirm, also the last slide's images aren't loaded if they are lazy loaded

**Comment by grloch** [comment] 2020-01-17 16:48
I can confirm this too, I use 4  slides per group:
```
var mySwiper = new Swiper('.swiper-container', {
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        }, slidesPerView: 'auto',
        freeMode: false,
        slidesPerGroup: 4,
        spaceBetween: 10,
        centerInsufficientSlides:true,
        loop: false,
    })
```

**Comment by milanwake** [comment] 2020-01-20 02:21
I also have this error. In earlier versions it was not.

**Comment by codesignist** [comment] 2020-01-25 07:26
I think this bug should related with this change:
https://github.com/nolimits4web/swiper/commit/cd87ce51fca74b6ddecb5c64618300d59bacc4c4#diff-a285802d362fd397a1e00fc52eb92e72

**Comment by codesignist** [comment] 2020-01-25 07:43
More details about this bug:
- If you make "centeredSlides: true" it works correctly.
- If you move your mouse slow it works well too. But when you move your mouse fast and on mouse up it suddenly stops.

**Comment by francesco-bizen** [comment] 2020-01-31 10:27
Encountered this bug today as well (and a lot of other ones too...).
What fixed it for me was declaring the same value for both slidesPerView and slidesPerGroup.

Also had a bug that would make the slider get stuck on resize from lower to higher resolution if i was on the last page. Basically if i was on last page with 2 slides, once i resize to show 3 slides the last slot would be empty and the whole slider would be off position. Resolved this by attaching a slideTo(0) action to the resize event.

**Comment by dangelion** [comment] 2020-02-01 10:42
Same problem here.

Thanks @francesco-bizen, adding `slidesPerGroup` with same value of `slidesPerView` solved, for me. 

Anyway, waiting for a proper bugfix from Swiper in the next release.

**Comment by fedemar** [comment] 2020-02-05 17:11
Adding slidesPerGroup with same value as slidesPerView prevents carousel from moving in any direction when the value is 'auto'.

**Comment by MMasey** [comment] 2020-02-06 10:58
I can also confirm that this bug is occuring. In my instance I am using `slidesPerView: "auto"` so the slidesPerGroup fix won't work for me. 

I had a quick check of @codesignist's PR #3414 and it seems to fix the issue.

**Comment by fedemar** [comment] 2020-02-06 13:08
@codesignist's PR #3414 fixed the issue for me

**Comment by nolimits4web** [comment] 2020-02-08 08:41
Fixed by #3414

**Closed by nolimits4web** 2020-02-08 08:41 UTC

**Comment by tarpagad** [comment] 2022-03-22 15:07
Looks like the bug just reappeared again : unable to reach the last 3-5 slides 🤔

**Comment by cgarrovillo** [comment] 2023-05-08 17:44
@nolimits4web

**Comment by sinansubasi95** [comment] 2023-07-10 09:38
I have the same problem.

**Comment by agalloch21** [comment] 2023-09-21 04:43
setting **touchReleaseOnEdges** to true solves my problem

**Comment by nuleongee** [comment] 2023-12-13 05:43
I solved it by adding **touchStartForcePreventDefault**

**Comment by gabemate** [comment] 2024-02-22 01:20
> setting **touchReleaseOnEdges** to true solves my problem

This fixed mine thanks for this

**Comment by SefyanKehail** [comment] 2024-04-26 10:29
You can reproduce the bug if you set a margin on the x axis on each swiper-slide.
I just make sure to use spaceBetween instead, that was it for me.

**Comment by santibh** [comment] 2024-10-08 07:54
Setting **freeMode** to true solves my problem
