### ISSUE TITLE
Scrolling on ios is awkward  

### ISSUE THREAD

**Issue by XAihan** [nolimits4web/swiper#6289] opened 2023-01-16 07:50 UTC
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/snowy-framework-1y9j6s?file=/src/App.vue

### Bug description

I created an instance. No problem when I run it in my browser. But when I opened it on my ios phone, swiping became awkward.

### Expected Behavior

Hope to solve this problem

### Swiper version

  "swiper": "^8.3.2",

### Platform/Target and Browser Versions

ios 15.7

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by fabianmarcus** [comment] 2023-01-16 17:00
I ran into the same problem even in Version 9 Beta. Had to disable swiping so the user has to use the controls for sliding.

**Comment by XAihan** [comment] 2023-01-17 02:52
https://github.com/nolimits4web/swiper/issues/6185
I see this,  I think it's the same problem, and the answer here tells me that there's no solution to this problem right now.

**Comment by liekki** [comment] 2023-01-26 10:17
Yes, seems to be a duplicate of https://github.com/nolimits4web/swiper/issues/6185

We are also experiencing this issue and, although it appears its a Chrome issue, we would love to find a solution to this.

**Closed** 2023-02-01 16:40 UTC
Labels: Vue
