### ISSUE TITLE
Swiper Last slide space

### ISSUE THREAD

**Issue by rockingaryan** [nolimits4web/swiper#3428] opened 2020-02-01 15:50 UTC
Hello,

I am trying to create a Slider which slide content when dragged with mouse.

Here is the same Slide https://swiperjs.com/demos/110-slides-per-view.html
Here is the similar one https://swiperjs.com/demos/150-freemode.html

This is a (multiple allowed):
* [ ] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

The Problem is with the last slide, which gives the empty space. I want to stop the drag when the slide ends without adding space but not found any solution. It gives no space when slide through the navigation but not works when dragged with Mouse.

![image](https://user-images.githubusercontent.com/34836534/73594800-b75c0380-4537-11ea-840f-5149b9b0f286.png)

![image](https://user-images.githubusercontent.com/34836534/73594820-e2deee00-4537-11ea-8005-15b0b4299296.png)

The Result I am looking for: (Get the Slide at end without space/reposition the slide bak to its position).
This demo is also using Swiper but I don't know the init code.
![2020-02-01 21-10-25 2020-02-01 21_15_57](https://user-images.githubusercontent.com/34836534/73594841-0dc94200-4538-11ea-8102-4ca0d75f23d2.gif)

How can i fix this?

Thanks.

**Comment by nolimits4web** [comment] 2020-02-05 12:10
Duplicate of #3398

**Closed by nolimits4web** 2020-02-05 12:10 UTC

**Comment by mohan-kumar-m-p** [comment] 2024-09-25 07:06
Im getting empty space while rendering swiper slide conditionally. If the condition is not satisfied then how come im getting empty space.
