### ISSUE TITLE
3.0.7 Pagination no clickable in horizontal mode

### ISSUE THREAD

**Issue by Dam720** [nolimits4web/Swiper#1265] opened 2015-05-04 15:19 UTC
Since 3.0.7 the pagination doesn't trigger click in horizontal mode. I'm on Chrome 43. This bug is in examples too .

**Comment by nolimits4web** [comment] 2015-05-09 12:31
It looks like a browser/environment problem. Duplicate of #1152 and the same in http://www.idangero.us/swiper/forum/#!/bugs-and-issues:nextbuttonprevbutton-doesn

**Closed by nolimits4web** 2015-05-09 12:31 UTC
