### ISSUE TITLE
[swiper react] controller module is not working

### ISSUE THREAD

**Issue by nethalayaswanth** [nolimits4web/swiper#4355] opened 2021-03-19 13:57 UTC
- Swiper Version:  swiper@6.4.5
- Platform/Target and Browser Versions:Windows, IOS, ANDROID, CHROME, ETC.

## What You Did

 tried to implement two way controller  by controller module using reacthooks

sandbox sample below

https://codesandbox.io/s/swiper-react-fork-forked-4v4we

## Expected Behavior

can control swiper instances mutually

## Actual Behavior

nothing really happening

**Comment by nolimits4web** [comment] 2021-03-22 08:46
Duplicate of #3852

**Closed by nolimits4web** 2021-03-22 08:46 UTC
Labels: React
