### ISSUE TITLE
Swiper does not work correctly on hybrid windows computers

### ISSUE THREAD

**Issue by DaanDD** [nolimits4web/swiper#2912] opened 2018-12-11 14:35 UTC
This is a:
* [x] bug

* Swiper Version: 4.2.2
* Platform/Target and Browser Versions: Windows 7, latest Google Chrome

### What you did
1. Fire up a Windows computer that has both a touch screen and a mouse
2. Open any of the Swiper demos on Google Chrome
3. Try swiping using the touch screen

### Expected Behavior
The Swiper instance should swipe along with my finger.

### Actual Behavior
The Swiper instance stops moving after a few pixels. If I then move my mouse without clicking, the Swiper instance moves along with my mouse.

### Possible solution
I managed to trace down the bug to an issue with the touch support detection in https://github.com/nolimits4web/swiper/blob/master/src/utils/support.js

For some reason, the `touch` flag gets set to `false`, even though my computer has a touch screen.

I managed to force the `touch` flag to true by adding the code below to my project:

```js
window.Modernizr = {
  touch: true,
};
```

**Comment by samuanv** [comment] 2018-12-11 15:49
Same issue detected here.

With @DaanDD  workaround to force the touch flag, it is not working on my Lenovo ThinkPad.

Is there any way to force the navigator or the swiper to behave as a touch device?

**Comment by nolimits4web** [comment] 2018-12-14 16:53
Duplicate of #2853

**Closed by nolimits4web** 2018-12-14 16:53 UTC
