### ISSUE TITLE
Swiper lags after first scroll

### ISSUE THREAD

**Issue by soliniak** [nolimits4web/swiper#3556] opened 2020-04-28 11:52 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 5.3.8
* Platform/Target and Browser Versions: Windows, Chrome Browser, **NOT APPLICABLE TO SMARTPHONES**
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-27-mousewheel-control-672gar?embed=1&file=index.html

### What you did
I've implemented swiper to simple project including few div's as a sliders

### Expected Behavior
Scroll from one slide to another using mouse wheel.

### Actual Behavior
Scroll works only from 1 -> 2 slide, to get to another slide (but not guaranteed) user is forced to intensify mouse scrolling. Adding sensitivity is not resolving this bug correctly.

**Comment by tsmladenova** [comment] 2020-04-30 13:30
Any chance you've found a solution? I have the exact problem but with horizontal scroll and I can find a proper solution. My designer found out that if you scroll the mouse really fast it scrolls to the next slide but that's not really an option...

**Comment by soliniak** [comment] 2020-05-06 18:06
Unfortunatelly I don't have solution to this problem :/ I noticed that this behaviour also exsists in swiper demos https://swiperjs.com/demos/

**Comment by tiadaguru** [comment] 2020-05-11 00:13
I found the regression, I _think_. For a workaround, does moving back to Swiper.js 5.2.0 work?

**Last known working:** 5.2.0
**First known bad:** 5.2.1

Thus, looks like #3328 is the culprit here. It _**perfectly**_ reproduces on https://swiperjs.com/demos/270-mousewheel-control.html

Chrome 81.0.4044.138 (64-bit)
Windows 10 Pro x64 18363.778
Logitech MX Master 2S (default Windows 10 driver)
**Swiper.js 5.2.1 and newer**

You can scroll, at most, _one_ slide normally before Swiper.js requires ~15 scroll wheel rotations. To any normal user, Swiper.js looks frozen using a horizontal scroll wheel.

Quirk: it only occurs with **vertical** scroll wheel events. Using my horizontal scroll wheel, Swiper.js behaves normally.

**Comment by tsmladenova** [comment] 2020-05-11 06:46
@tiadaguru I've just checked what version I'm using and turns out I've switched way back to 4.4.0. Swiper works normally and it doesn't seem to have the scrolling problem.

**Comment by nolimits4web** [comment] 2020-05-11 14:23
Closing as duplicate of #3420

**Closed by nolimits4web** 2020-05-11 14:23 UTC
