### ISSUE TITLE
Touch drag no longer works

### ISSUE THREAD

**Issue by jwoodwardtfx** [nolimits4web/swiper#3772] opened 2020-08-21 11:29 UTC
There is a bug introduced by the change "Simplify touch events detection" (11dcfe5).

It looks like there has been an attempt to simplify detection of "touch" support, however the way it's been changed will break most desktop/tablet use cases.

The newer code uses either:

'ontouchstart' in window => this has been deprecated and taken out of Chrome for ages (https://www.chromestatus.com/feature/4764225348042752)
DocumentTouch => this has been removed from the standards and shouldn't be used either (https://developer.mozilla.org/en-US/docs/Web/API/DocumentTouch)
The old method checks for "window.navigator.maxTouchPoints", which (at least on Windows desktop/tablets) will function correctly.

This commit needs reverting.

See also issues 3589 and 3649.

**Comment by ksn-systems** [comment] 2020-08-23 23:16
I Have had the same issue with 6.1.2 on Chrome.

However 5.4.0 is also broken on Chromium / linux 

My fallback release is 5.3.8 where swiping works everywhere but the current page blinks on both Chrome windows and Chromium / Linux as the start of a drag / swipe

**Comment by matadorhernan** [comment] 2020-08-24 09:43
Yeah I need to fallback as well, the swiper api is now broken for anything that isnt either an IOs or an Android device, I agree with the author of this issue

**Comment by jwoodwardtfx** [comment] 2020-09-04 14:40
Any further progress on this?

Thanks.

**Comment by ksn-systems** [comment] 2020-09-07 20:33
Just tried 6.0.2 on Chromium / linux 

Touch drag is still Broken.

**Comment by antiero** [comment] 2020-09-15 17:03
Is the current workaround for this to revert to using 5.3.8?

**Comment by jwoodwardtfx** [comment] 2020-09-16 07:32
Yes that is one workaround, but I use Framework7 which includes Swiper. I've had to manually hack the code to revert this change.

It's looking like Swiper is becoming a dead project for anything other than a Android/iOS Smartphone as there seems to be no desire to fix this issue, which basically stops use of Swiper on any Windows-based tablet.

**Comment by wizardnet972** [comment] 2020-09-18 15:33
So many problems it caused my clients.
28+ days and yet no fix :(
Demos are not working (stackblitz). 
Sad.

**Comment by wizardnet972** [comment] 2020-09-18 15:35
This problem should be critical.
Many problems it caused to me and my clients.
28+ days and yet no fix :(
Demos are not working (stackblitz).
Sad.

**Comment by mberezinski** [comment] 2020-11-20 13:54
Any progress? Demo https://swiperjs.com/demos/ is not working on any touch enabled windows system like Microsoft Surface devices.

**Comment by vltansky** [comment] 2020-12-31 14:50
Duplicate of #3728 
Also, there is some workaround there.

**Closed by vltansky** 2020-12-31 14:50 UTC

**Comment by vltansky** [comment] 2020-12-31 14:51
Also, there is some workaround there
