### ISSUE TITLE
Swipe gestures dont work on tablet or desktop

### ISSUE THREAD

**Issue by antonioberetini** [nolimits4web/swiper#3649] opened 2020-07-03 14:03 UTC
I tested swiper components on windows machine with touch interface, swipe gestures don't work. I tried this out in Chrome and Chromium Edge. Is this a known issue? I am working on a progressive web app which is targeting touch enabled tablets with windows

**Comment by kebien6020** [comment] 2020-07-04 08:58
In #3589  there is a couple of cases with similar issues.

**Comment by vltansky** [comment] 2020-12-31 14:46
Duplicate of #3772

**Closed by vltansky** 2020-12-31 14:46 UTC
