### ISSUE TITLE
Swiping on iOS 14.5/14.6 in latest Chrome Version slow and hangs

### ISSUE THREAD

**Issue by kolorfilm** [nolimits4web/swiper#4493] opened 2021-04-28 08:08 UTC
- Swiper Version: 6.5.7
- Platform/Target and Browser Versions: iOS 14.5 Chrome 87.0.4280.163 (Safari in latest version works!)

## What You Did

Just swiping, you can see it as well in your own demo and here (default) : https://stackblitz.com/edit/swiper-demo-1-default?file=index.html

Swiping hangs and is quite slow.

## Expected Behavior

Smooth swiping

## Actual Behavior

Swiping is slow and hangs.

_iOS 14.5 Chrome 87.0.4280.163 (the broken one):_
https://user-images.githubusercontent.com/26705027/116368514-b3856280-a808-11eb-8950-76ca063f5b28.mp4

_iOS 14.4.2-Chrome 87.0.4280.163 (the good one):_
https://user-images.githubusercontent.com/26705027/116369385-9d2bd680-a809-11eb-9bfe-8ddfbff42d82.MP4

**Comment by Alldar** [comment] 2021-04-28 17:43
Safari has the same issues on

Swiper Version: 6.5.8
Platform/Target and Browser Versions: iOS 14.5 Safari version

https://user-images.githubusercontent.com/905204/116448796-2c64d880-a862-11eb-8a30-c33a66139445.MP4

**Comment by CodeWithOz** [comment] 2021-04-29 15:02
@kolorfilm @Alldar what was the last version you know that didn't have this problem? I want to upgrade but I'd like to avoid this until it's fixed.

**Comment by nolimits4web** [comment] 2021-04-29 15:06
On iOS 14.5 can’t see anything like that in Chrome and in Safari

**Comment by kolorfilm** [comment] 2021-05-03 17:25
> @kolorfilm @Alldar what was the last version you know that didn't have this problem? I want to upgrade but I'd like to avoid this until it's fixed.

I only know iOS 14.4.2 didn‘t have this problem. It seems it is a general problem by chrome.:

https://piunikaweb.com/2021/04/22/chrome-content-on-ios-gets-squashed-on-changing-orientation-for-some/

This workaround there seems to fix the problem. Of course this is not a good option as normal users won‘t change that setting.

**Comment by srg-b** [comment] 2021-05-07 16:58
we've seen a 25% click-through drop on the carousels using the swiper for devices running iOS 14.5.x, compared to those running 14.4.2

**Comment by tschortsch** [comment] 2021-05-19 10:22
I'm having the same issue with Chrome 90.0.4430.78 on iOS 14.5.1. The swiping animation is really laggy/buggy. In Safari it seems to be ok for me.
As @kolorfilm mentioned the issue can be reproduced on the demos page of swiper: https://swiperjs.com/demos

**Comment by tschortsch** [comment] 2021-05-20 15:25
As a workaround I could switch to using the `cssMode` when the website is opened with Chrome for iOS 14.5. Of course this can only be done if you don't rely on a lot of fancy features which aren't supported with the `cssMode`.

Here is the helper function which I'm using to detect Chrome for iOS 14.5:
```
const isChromeForIOs145 = () => {
	const userAgent = window.navigator.userAgent;
	const isChromeForIOs = /CriOS/i.test(userAgent);
	if (isChromeForIOs) {
		const iOsMatch = userAgent.match(
			/(.+)(iPhone|iPad|iPod)(.+)OS[\s|\_](\d+)\_?(\d+)?[\_]?(\d+)?.+/i
		);
		if (iOsMatch && iOsMatch.length >= 6) {
			const iOsVersionMajor = parseInt(iOsMatch[4], 10);
			const iOsVersionMinor = parseInt(iOsMatch[5], 10);
			if (iOsVersionMajor >= 14 && iOsVersionMinor >= 5) {
				return true;
			}
		}
	}
	return false;
}
```

**Comment by tschortsch** [comment] 2021-06-02 13:52
The issue seems to be fixed in iOS 14.6. Can anybody confirm?

**Comment by malininss** [comment] 2021-06-10 08:31
I have the same problem, the bug is reproduced in iOS 14.5 (iPhone 12 mini) in safari and in iOS 14.6 (iphone 12 pro) in Chrome.
Unfortunately, the cssMode isn't to suit for me

**Comment by realityfilter** [comment] 2021-06-10 09:27
I noticed it on my iPad pro only. In normal Safari. Restarting the device fixed it for me. So I think it is more an iOS / Safari bug.

**Comment by PhilipCrumpton** [comment] 2021-06-10 14:26
I can confirm both the bug and that cssMode: true resolves the issue (with reduced features of course). Big thanks to @tschortsch for the helper function!

**Comment by artshevtsov** [comment] 2021-06-19 19:51
Nothing changes. I made this video 1 year ago https://youtu.be/gev1PvGWsKg
animation becomes smooth after chrome mobile restart

**Comment by az-vm** [comment] 2021-06-21 22:34
Hello

With IOS 14.6 on safari and firefox, works well, but on google chrome, still not smooth swiping.

Any workaround on this yet ?

**Comment by heitorb** [comment] 2021-06-22 17:25
Weird behavior. I had it working smoothly always with Angular 11 on iPhone Chrome. Updated to 12 and started seeing the clunky behavior. It is on iPhone Chrome only. I saw one of the posts saying that restarting fixes it. I did that and it indeed fixed it, but if I clear my chrome cache, it starts happening again, unless I restart.

**Comment by mingttong** [comment] 2021-07-05 07:53
Swiper Version: 6.7.0  

I had the same problem in IOS 14.6, it will appear on the webview of our app, but works well on browser. And I found that using **transition & translate3d/translate** to do animation will slow and hangs (use margin & transition is fine) in IOS 14.6, and Swiper uses **transition & translate3d** to do animation.  

My solution is to implement the animation myself:
In the `setTranslate` event of swiper, set `transitionDuration` to empty, set `translate` back to the original value, and then implement the animation by yourself through `requestAnimationFrame`. It works well in IOS 14.6.

```javascript
function easeOut(currentTime, startValue, changeValue, duration) {
    currentTime /= duration;
    return -changeValue * currentTime * (currentTime - 2) + startValue;
}

function getTransitionSimulator(ele, distance, duration, callback) {
    let handle;
    let resolve;
    return () => {
        let promise = new Promise(res => {
            resolve = res;
        });
        let startTime = performance.now();
        cancelAnimationFrame(handle);
        function _animation() {
            let current = performance.now();
            // distance to move this frame
            let disVal = easeOut(current - startTime, 0, distance, duration);

            callback(ele, disVal);
            if ((current - startTime) / duration < 1) {
                handle = requestAnimationFrame(_animation);
            } else {
                cancelAnimationFrame(handle);
                resolve();
            }
        }
        handle = requestAnimationFrame(_animation);
        return promise;
    };
}

swiper.on('setTranslate', (swiper, targetTransVal) => {
    const wrapper = swiper.$wrapperEl[0]; // wrapper element
    // when use transition to do animation
    if (wrapper.style.transitionDuration !== '0ms') {
        // get origin translate value
        const curTransVal = this.swiper.getTranslate();
        // cancel the animation of transition
        wrapper.style.transitionDuration = '';
        wrapper.style.transform = `translate3d(${curTransVal}px, 0px, 0px)`;

        // use requestFrameAnimation to do animation my self
        const transSimulator = getTransitionSimulator(wrapper, targetTransVal - curTransVal, 300, (el, val) => {
            el.style.transform = `translate3d(${curTransVal + val}px, 0px, 0px)`;
        });
        await transSimulator();
        // End the transition, call the callback (simulate the internal implementation of Swiper)
        swiper.onSlideToWrapperTransitionEnd.call(wrapper, { target: wrapper });

    }
})
```

**Comment by rubenmeines** [comment] 2021-07-09 09:29
I have this issue as well os Chrome for iOS. You can see it by going to the https://swiperjs.com/demos on your mobile iOS device and just swipe. I have iOS 14.6 - iPhone SE from 2021.

**Comment by m1911star** [comment] 2021-07-13 05:17
I'm using 6.7.5 with virtual slides feature, it's slow in ios 14, cssMode is not suite for me

**Comment by emgerold** [comment] 2021-07-13 15:55
Same issue with swiper v6.7.5 on iOS 14.6 (iPad Air 4th Gen)

**Comment by peace195** [comment] 2021-07-25 09:14
I have same issue on iOS 14.5 and 14.6 on Mobile Chrome. Safari is ok. **Is it iOS bug or Swiper bug?**

**Comment by peace195** [comment] 2021-07-25 09:38
Is this attribute of css "transition: transform ease-out" affect?

**Comment by jfarris587** [comment] 2021-07-28 18:35
Similar to @peace195 This is a problem in iOS 14.6 on Mobile Chrome, However, this is not a problem with safari mobile. Its smooth in safari but lags in chrome mobile.

**Comment by icy-meteor** [comment] 2021-08-22 05:42
Are we hoping to get a fix for this soon or is there any workaround?

**Comment by nolimits4web** [comment] 2021-08-22 06:59
Closing as not related to Swiper

**Closed by nolimits4web** 2021-08-22 07:00 UTC
