### ISSUE TITLE
Thumbs in React is not working on version ^6.3.0

### ISSUE THREAD

**Issue by DCitalo** [nolimits4web/swiper#3852] opened 2020-10-02 15:42 UTC
This is a (multiple allowed):
* [x] bug

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions: Possibly all plataforms

### What you did
I followed exactly what Timo did in his [video tutorial](https://www.youtube.com/watch?v=l4kFO6VQPfA&feature=emb_logo). But on my code it was not working, so i tryed to [copy his code](https://github.com/valnub/swiper-react-demo/blob/master/src/App.js), and it still wasn't working... In last resource I downgrade to version 6.0.2, the same version that is used on the video, just after that the thumbs work perfectly. I don't know exactly version that broken between 6.0.2 - 6.3.2 but in the last version the Thumbs aren't working.

### Expected Behavior
Thumbs to control the main carousel

### Actual Behavior
Click in thumbs and nothing happens

#### Edit 08/12/2020
I've [recorded an loom](https://www.loom.com/share/ad358f835c6d43bcae3632a5c2ae7ec6) and [create a codesandbox for this](https://codesandbox.io/s/vigilant-lamarr-7fvkn?file=/src/App.js)

**Comment by spgwebdev** [comment] 2020-10-13 16:01
can confirm the issue is still present in 6.3.3

**Comment by ygj6** [comment] 2020-12-03 03:51
@DCitalo I've used the `master` branch test and there's no problem.

**Comment by DCitalo** [comment] 2020-12-08 18:16
@ygj6 I've used the master as well, as you can see in the codesandbox I posted in 14 Oct. 
I've record a loom with the error, if you can see in the release `6.2.0` it was working but in the release `=> 6.3.0` it is not working:
https://www.loom.com/share/ad358f835c6d43bcae3632a5c2ae7ec6

Btw in the last release (`6.4.0`) it still not working

**Comment by code-mat** [comment] 2020-12-14 00:03
it doesn't work still in `6.4.1` :(

**Comment by valnub** [comment] 2021-02-10 14:31
I can confirm this issue still exists in 6.4.5, see https://github.com/valnub/swiper-react-demo/issues/4

As Swiper is open source let's have a look at the source code. There must have been a change somewhere between version 6.0.2 and 6.3.0. If we can find the problem maybe we can send in a PR to fix it.

**Comment by nolimits4web** [comment] 2021-02-11 15:55
For me it seems like some bug in React, if you disable StrictMode it works.
Replace this:
```
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  rootElement
);
```
with this:
```
ReactDOM.render(
  <App />,
  rootElement
);
```
and everything works

**Comment by SinazoBogicevic** [comment] 2021-03-17 20:45
> For me it seems like some bug in React, if you disable StrictMode it works.
> Replace this:
> 
> ```
> ReactDOM.render(
>   <React.StrictMode>
>     <App />
>   </React.StrictMode>,
>   rootElement
> );
> ```
> 
> with this:
> 
> ```
> ReactDOM.render(
>   <App />,
>   rootElement
> );
> ```
> 
> and everything works

This worked for me

**Comment by nolimits4web** [comment] 2021-04-16 16:12
Fixed by #4440

**Closed by nolimits4web** 2021-04-16 16:12 UTC
Labels: React

**Comment by tariqmurtuza** [comment] 2021-05-09 10:50
Thumb issue is fixed in latest version  v6.5.9. if someone is having the issue of thumb please update your plugin.

**Comment by Waqasamir** [comment] 2022-08-23 07:23
> Thumb issue is fixed in latest version v6.5.9. if someone is still having the issue of thumb please update your plugin.

still not work in swiper 8.3.2

**Comment by AJ-1009** [comment] 2022-08-26 03:19
Same not working in swiper 8.3.1

**Comment by AlkenD** [comment] 2022-09-07 16:41
Its still not working in Swiper 8.3.2

**Comment by hthuanweb** [comment] 2022-09-09 03:48
> For me it seems like some bug in React, if you disable StrictMode it works. Replace this:
> 
> ```
> ReactDOM.render(
>   <React.StrictMode>
>     <App />
>   </React.StrictMode>,
>   rootElement
> );
> ```
> 
> with this:
> 
> ```
> ReactDOM.render(
>   <App />,
>   rootElement
> );
> ```
> 
> and everything works ✌️

**Comment by solankeys** [comment] 2022-11-07 04:10
I am using version 8.4.4 of swiper, react 18 and typescript, it works if you define type as any for the state (const [thumbsSwiper, setThumbsSwiper] = useState<any>();) like this

**Comment by solankeys** [comment] 2022-11-07 04:12
define type as any for thumbSwiper state, it worked for me
