### ISSUE TITLE
Chrome sometimes  click does nothing.

### ISSUE THREAD

**Issue by Valonix** [nolimits4web/Swiper#1256] opened 2015-04-27 10:09 UTC
var mySwiper = new Swiper ('.mainslider', {
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        slidesPerView: 1,
        loop: true
    });

but, if in console i write $(".swiper-button-prev").click();  slider will show a new slide.

This problem i see in your demo site too. This mean, its not my HTML or JS problem.

**Comment by nolimits4web** [comment] 2015-04-27 12:04
It looks like a browser/environment problem. Duplicate of #1152 and the same in http://www.idangero.us/swiper/forum/#!/bugs-and-issues:nextbuttonprevbutton-doesn

**Closed by nolimits4web** 2015-04-27 12:04 UTC

**Comment by klaussilveira** [comment] 2016-11-18 22:59
@nolimits4web why was this closed? It wasn't fixed.
