### ISSUE TITLE
Swiper downloading both WEBP and PNG when picture tag is used as swiper-slide.

### ISSUE THREAD

**Issue by gswierczynski** [nolimits4web/swiper#3127] opened 2019-06-28 18:22 UTC
This is a (multiple allowed): bug possibly or maybe lack of picture tag support

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS, Chrome
* Live Link or JSFiddle/Codepen or website with issue: https://motolog.app

### What you did
I have a slide like this:
```html
<div class="swiper-slide">
    <picture>
        <source
                type="image/webp"
                srcset="assets/img-webp/web_6_360w.webp 360w,
             assets/img-webp/web_6_720w.webp 720w,
             assets/img-webp/web_6_1080w.webp 1080w,
             assets/img-webp/web_6.webp 1440w"
                sizes="(min-width: 1200px) 25vw, (min-width: 768px) 33vw, 100vw"/>
        <source
                type="image/png"
                srcset="assets/img/web_6_360w.png 360w,
             assets/img/web_6_720w.png 720w,
             assets/img/web_6_1080w.png 1080w,
             assets/img/web_6.png 1440w"
                sizes="(min-width: 1200px) 25vw, (min-width: 768px) 33vw, 100vw"/>

        <img class="img-fluid"
             srcset="assets/img/web_6_360w.png 360w,
         assets/img/web_6_720w.png 720w,
         assets/img/web_6_1080w.png 1080w,
         assets/img/web_6.png 1440w"
             sizes="(min-width: 1200px) 25vw, (min-width: 768px) 33vw, 100vw"
             src="assets/img/web_6.png" alt="">
    </picture>
</div>
```
The WebP is downloaded first, but then later on PNG is also requested.
It does not happen every time, but "Empty Cache and Hard Reload" can force it.
It seems that the initial slide is not affected by this.

Here is the stack trace:
<img width="267" alt="Screenshot 2019-06-28 at 20 13 47" src="https://user-images.githubusercontent.com/3669529/60362534-75873f80-99e1-11e9-8607-60e9062c81b4.png">

### Expected Behavior
I would expect only the WEBP version of the image to be used.

### Actual Behavior
The WEBP is used, but later on swiper.js is pulling also PNG.

I am no JS expert, please excuse me if there is something obvious that I am missing here.

Thanks for your great work.

**Comment by AntoninBeaufort** [comment] 2019-10-18 11:15
Same problem on 4.5.0 :/
![download_web_and_jpeg](https://user-images.githubusercontent.com/33757018/67090038-6226fc80-f1a9-11e9-9b9b-aa95ec807fc1.PNG)
![download_webp_and_jpeg](https://user-images.githubusercontent.com/33757018/67090039-6226fc80-f1a9-11e9-913e-dee84d7a9612.PNG)

**Comment by Quirksmode** [comment] 2019-11-08 13:58
Same problem for me, it's really adding to the page weight, is there a fix in sight?

**Comment by hatto** [comment] 2020-01-17 15:32
seems to be fixed in the version 5.3 (but wasn't in 5.0.4)

**Comment by parisek** [comment] 2020-01-20 08:48
For us not fixed in version 5.3

**Comment by Avlexz** [comment] 2020-01-30 15:50
Setting preloadImages: false, when initializing, seems to stop this behaviour.

**Comment by parisek** [comment] 2020-01-30 19:16
Yes I can confirm it will fix it, thank you @Avlexz :)

**Comment by lriebandt** [comment] 2020-01-31 07:39
but in my case setting `preloadImages` to `false` has sideeffects. e.g. the size of the slides isn't correct

**Comment by Avlexz** [comment] 2020-01-31 08:06
@lriebandt if I'm not mistaken, setting preloadImages to false shouldn't cause that. You can control the size of your slides using slidesPerView and slidesPerGroup.

**Closed** 2020-09-27 11:44 UTC
Labels: wontfix
