### ISSUE TITLE
How can I enable bounce effect while swiping to the last slider

### ISSUE THREAD

**Issue by wt680304** [nolimits4web/swiper#3418] opened 2020-01-27 13:37 UTC
when I slide horizontally,it bounce back while sliding to the first slider,but it doesn't bounce back while sliding to the last slider,how can I enable bounce effect while sliding to the last slider?

**Comment by fedemar** [comment] 2020-02-01 20:56
Same ask here.
Leaving a screenshot taken from Swiper Demos for clarification.

![image](https://user-images.githubusercontent.com/5452635/73598862-101da300-451c-11ea-9d4c-7fc9f9382098.png)

**Comment by nolimits4web** [comment] 2020-02-05 12:10
Duplicate of #3398

**Closed by nolimits4web** 2020-02-05 12:10 UTC
