### ISSUE TITLE
Classes is not working as expected

### ISSUE THREAD

**Issue by gyto23** [nolimits4web/swiper#4020] opened 2020-12-08 17:56 UTC
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5.

### What you did
I have looked into the implementation of the Swiper React version and looks like most of the classes that available in is not editable. https://github.com/nolimits4web/swiper/blob/2d6c2539f6ee3faf4fb7dbd966008f7beed7130f/src/react/swiper.js#L162

### Expected Behavior
Original Swiper API was supporting a class change or adding additional class to the existing swiper config option. I am expecting it will be transfer it as is, but as I start looking more deeply, I found most of the classes are static and cannot be changed. 

### Actual Behavior
```
     <Swiper
        initialSlide={startIndex}
        spaceBetween={60}
        className={classNames(styles.swiperContainer, styles.galleryMain)}
        slideClass={styles.gallerySlide} // doesn't work
        wrapperClass={styles.galleryWrapper} // doesn't work
        zoom={{
          zoomedSlideClass: styles.gallerySlideZoomed, // doesn't work
          containerClass: styles.gallerySlideZoomContainer, // doesn't work
        }}
        thumbs={{
          swiper: thumbInstance,
          slideThumbActiveClass: styles.galleryThumbActive, // doesn't work
        }}
        navigation={{
          nextEl: `.${styles.galleryArrowNext}`, // doesn't work
          prevEl: `.${styles.galleryArrowPrev}`, // doesn't work
          disabledClass: styles.galleryArrowDisabled, // doesn't work
          hiddenClass: styles.galleryArrowHidden, // doesn't work
        }}
      >
 ...
```

**Comment by vltansky** [comment] 2021-01-21 22:38
relevant to Vue, Svelte and Angular too.
All classes should be used from params.

**Comment by nolimits4web** [comment] 2021-01-25 16:32
Sorry, closing this as this is by design. Those namespace class names are designed only to be used with Core version, and not supported by React/Vue/Svelte/Angular components. If you need custom class on slides, just add one in addition to `swiper-class`.

**Closed by nolimits4web** 2021-01-25 16:32 UTC
Labels: Angular, React, Svelte, Vue, feature request, good first issue
