### ISSUE TITLE
Last slides never active when slidesPerView > 1 or 'auto'

### ISSUE THREAD

**Issue by udovichenko** [nolimits4web/Swiper#1257] opened 2015-04-28 10:43 UTC
Regarding to this question https://stackoverflow.com/questions/29414642
I've made an single-row example http://codepen.io/anon/pen/LVEJYq

The problem is when slidesPerView > 1 or 'auto', then we can never get last N slides active 
(last 3 slides in example).
Even if we use with slideTo() function.

If it is by design, then the special option is necessary to let last slides be activated.

Otherwise it looks strange, especially, if one swiper controlls another 
(fullscreen gallery with previews).

Activation of last slides works properly when centerSlides is enabled, 
but centerSlides is sometimes incompatible with the page appearance...

**Comment by nolimits4web** [comment] 2015-04-28 19:43
Sorry, was discussed many times. Active index and every other indexes in Swiper depends on its position and layout, so it also will be strange if Swiper will not move or do anything else, but still switching active index/class on slides, no much sense in this. 

If you need something depending on such logic, then you need custom solution by checking index and adding custom classes

So closing this issue as it is by design

**Closed by nolimits4web** 2015-04-28 19:43 UTC
