### ISSUE TITLE
Pagination buttons don't show on Sveltekit project

### ISSUE THREAD

**Issue by analubarreto** [nolimits4web/swiper#4590] opened 2021-05-20 14:50 UTC
- Swiper Version: 6.6.2
- Platform/Target and Browser Versions: macOS - Chrome
## What You Did

https://codesandbox.io/s/black-wind-on3qc
I'm using it with sveltekit, to reproduce:
npm init svelte@next (sveltekit demo app -> no -> no -> no)
npm install
npm install swiper
npm run dev
create a new component inside lib
copy the code to the new component and use inside a page

## Expected Behavior

Pagination should work fine with either Svelte or Sveltekit

## Actual Behavior

Animation shows, but buttons don't on Sveltekit

**Comment by nolimits4web** [comment] 2021-05-20 14:54
Duplicate of #4574

**Closed** 2021-05-20 14:54 UTC
Labels: Svelte

**Comment by analubarreto** [comment] 2021-05-20 15:02
It's really not it's pagination not navigation, just because I have used his instructions doesn't mean it's the same issue u_u

**Comment by tonprince** [comment] 2021-05-27 02:15
I have the same issue, the pagination icons do not show with Sveltekit.

**Comment by 0line** [comment] 2021-06-02 01:46
I found a way to solve it, I'm passing you the code that I implemented in svelte kit. 

`<script  lang="ts">
   	import Swiper from 'swiper';
    import 'swiper/swiper.scss';
    import 'swiper/components/navigation/navigation.scss';
    import 'swiper/components/pagination/pagination.scss';
    
	import { onMount } from 'svelte';
	import { browser } from '$app/env';

 	let SwiperCore,Navigation,Autoplay,Lazy,Pagination ; 
	if (browser) {
		onMount(async () => {
			SwiperCore  = (await import('swiper')).default;
			Navigation = (await import('swiper')).Navigation;
			Pagination = (await import('swiper')).Pagination;
			Autoplay = (await import('swiper')).Autoplay;
			Lazy = (await import('swiper')).Lazy;
			SwiperCore.use([Navigation,Pagination,Autoplay,Lazy]);
			const swiper = new Swiper('.swiper-container', {
				speed: 400,
				spaceBetween: 0,
				autoplay: {
					delay: 4000,
				},
				slidesPerView: 1,
				preloadImages: false,
				// Enable lazy loading
				lazy: {
					loadPrevNext: true,
				},
				navigation: {
					nextEl: '.swiper-button-next',
					prevEl: '.swiper-button-prev',
				},
				pagination: {
					el: '.swiper-pagination',
					type: 'bullets',
					clickable:true,
					dynamicBullets:true
				},
				effect: 'fade',
				fadeEffect: {
					crossFade: true
				},
			});
		});
	}
</script>`

<div class="swiper-container">
  
  <div class="swiper-wrapper">
    
    <div class="swiper-slide">Slide 1</div>
    <div class="swiper-slide">Slide 2</div>
    <div class="swiper-slide">Slide 3</div>
    ...
  </div>
  
  <div class="swiper-pagination"></div>

  
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>

  
  <div class="swiper-scrollbar"></div>
</div>


<div class="swiper-container">
  
  <div class="swiper-wrapper">
    
    <div class="swiper-slide">Slide 1</div>
    <div class="swiper-slide">Slide 2</div>
    <div class="swiper-slide">Slide 3</div>
    ...
  </div>
  
  <div class="swiper-pagination"></div>

  
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>

  
  <div class="swiper-scrollbar"></div>
</div>

**Comment by JimNayzium** [comment] 2024-07-17 19:59
I was searching all over for this, also but solved it with the simplest thing in svelte kit. 
I am in swiper version 11.
the first was to import the Nav/Pag form the modules folder instead of the 'swiper' location.
`    import { Navigation, Pagination } from 'swiper/modules';
`
