### ISSUE TITLE
Resetting transition-duration to 0 and triggering onSlideChangeEnd takes too long

### ISSUE THREAD

**Issue by wgroenewold** [nolimits4web/Swiper#1402] opened 2015-08-19 08:10 UTC
I have a fullscreen vertical swiper with speed: 2000, nothing special. When the slide has already completely transitioned to the next one it still takes 2 seconds to reset the transition-duration to 0 and trigger onSlideChangeEnd. I guess it has something to do with the default logarithmic movement of the swiper that doesn't get rounded/floored proper, so that it looks like the slide is already fully transitioned on screen, but not in the calculation. However my math is really rusty so I couldn't figure it out myself ;) Any help on this one would be really appreciated since I think it would also fix nolimits4web/Swiper#1401

**Comment by nolimits4web** [comment] 2015-08-20 20:36
I can't replicate this issue, but it seems like something wrong with settings or layout. Do you have an example or JSFiddle where i can see this issue?

**Comment by nolimits4web** [comment] 2015-08-22 15:39
Ok, it had time to figure this out. But the issue is with Chrome itself. For some weird reason until you scroll mouse wheel, transitionEnd event doesn't occur, this is strange as they don't related to each other

**Comment by wgroenewold** [comment] 2015-08-26 12:34
Made a JSFiddle because I noted some other weird issues concerning this as well:

http://jsfiddle.net/cztaLL81/

If you look in the Chrome Inspector you'll see an transition-duration of 0ms on init. During a slide it sets itself to 2000ms, but when the slide is already changed in the screen the duration is still 2000ms. Then after a short time it resets itself back to 0ms. 

I was wondering if this was coming because the calculation is still not really at 0, but the slider looks to be completed or that this is something different?

Also as you might noted, if you keep scrolling the Swiper never resets back to 0ms, but I think this is the Chrome bug you spoke about.

**Comment by nolimits4web** [comment] 2015-08-26 19:14
It is a Chrome issue. You can even check the following swipe up/down and then keep scrolling mousewheel, transition end will not occur until you stop scrolling mousewheel. Nothing common with calculation, just a Chrome issue, probably new, which doesn't trigger transitionEnd event until you scroll mouse

**Comment by nolimits4web** [comment] 2015-10-10 11:33
Closing due to Chrome issue https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=transitionend&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=534246

**Closed by nolimits4web** 2015-10-10 11:33 UTC
