### ISSUE TITLE
Mousewheel events being missed on Chrome when scrolling through trackpad

### ISSUE THREAD

**Issue by amitsaxena** [nolimits4web/Swiper#1734] opened 2016-06-07 13:59 UTC
I am using the following example:
http://idangero.us/swiper/demos/20-mousewheel-control.html

When I try scrolling on Chrome (multiple OS) via trackpad, there is a significant lag and it is very slow. Additionally it gets stuck at times (after a few slides) and looks like the events are being missed altogether.

I tried it on:
Chrome Version 50.0.2661.102 (64-bit)
OSX 10.11.5 (El Capitan)

but it also happens on Ubuntu Chrome. Works well on FF and other browsers.

**Comment by teddykishi** [comment] 2016-10-30 16:09
I've got the same on 
Chrome Version 53.0.2785.116 (64-bit)
OSX 10.12.1 (Sierra)

**Comment by DaPo** [comment] 2017-04-04 12:48
Same issue here!

Tested on macOS 10.12.3 with the trackpad of my MacBook Pro 15" mid 2015 on: 

1. Firefox 52.0.2
2. Google Chrome Version 56.0.2924.87
3. Safari Version 10.0.3

Regardless this issue, Swiper is a very nice plugin and I love using it. The API is very great.

**Comment by logan-jobzmall** [comment] 2017-09-01 00:55
Yep! Duplicate of #2086

**Comment by nolimits4web** [comment] 2017-11-13 10:35
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2017-11-13 10:35 UTC
