### ISSUE TITLE
"Touch slider" freezes when you touch it

### ISSUE THREAD

**Issue by dreit-p** [nolimits4web/swiper#4058] opened 2020-12-17 18:39 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.1
* Platform/Target and Browser Versions: Chromebook, Chrome OS 85. 
* Live Link or JSFiddle/Codepen or website with isssue: [https://swiperjs.com/](https://swiperjs.com/)

### What you did
I [touch the slider on my touchscreen](https://photos.app.goo.gl/ofnx7yqXPdVejRz7A) or in [devtool with mobile mode](https://i.imgur.com/Po6WdXJ.gif).
I've noticed if I reload page with started Mobile Mode in devtools then everything is okay. And that's why I can guess the problem is with initialization.
I want to note that [any other sliders](https://photos.app.goo.gl/BKQNUETcexJBphUU8) do not have this problem, so it can be solved.

### Expected Behavior
Smooth and great touch slider.

### Actual Behavior
Freezes and lags on every touch.

**Comment by vltansky** [comment] 2021-01-22 09:42
duplicate of #3728

**Closed by vltansky** 2021-01-22 09:42 UTC
