### ISSUE TITLE
Scrollwheel + Chrome / FF / Safari - won't work unless cursor is moved

### ISSUE THREAD

**Issue by drawcard** [nolimits4web/Swiper#1431] opened 2015-09-08 23:06 UTC
Hi,

I have found a bug on the [Swiper mousewheel demo page](http://www.idangero.us/swiper/demos/20-mousewheel-control.html) where the scrollwheel action works once, but will not scroll a second time unless the cursor has been moved substantially around the page by the user. For instance, you can't scroll up or down multiple times, without repositioning the cursor to another location. 

This occurs on the latest versions of Chrome / Firefox / Safari. Happens both with a Magic Mouse and the system trackpad.

My system: 

Model Name:	MacBook Pro (Retina 2015)
  Model Identifier:	MacBookPro11,5
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

**Comment by drawcard** [comment] 2015-09-12 12:36
I think the problem might be related to the physics-based scrolling of the Magic Mouse / Trackpad used by Macs. If I scroll with a gentle, small motion on either device, the panes advance normally as they should. However if I make a large, rapid sweeping motion with my finger, the panes won't move.

**Comment by drawcard** [comment] 2015-09-13 08:33
I think my problem is related to this: https://github.com/nolimits4web/Swiper/issues/1312. [This solution](https://github.com/nolimits4web/Swiper/issues/1312#issuecomment-132479142) didn't work for me either.

**Comment by nolimits4web** [comment] 2015-09-13 12:23
Yes, it is basically the same as #1312. And yes, there is a some kind of scroll "lock" because of intertia scrolling on OSX. 

Closing it as duplicate of #1312

**Closed by nolimits4web** 2015-09-13 12:23 UTC
