### ISSUE TITLE
Autoplay just plays one time - v10.3.0

### ISSUE THREAD

**Issue by zzseba78** [nolimits4web/swiper#7060] opened 2023-09-22 15:32 UTC
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/zzseba78-the-reactor/pen/BavYLpQ

### Bug description

Autplay plays one time and then stops if `disableOnInteraction: true` ( or not set, defaults to true ) and no interaction on the slider at all. Works as expected if `disableOnInteraction: false`

### Expected Behavior

Autoplay plays as always.

### Actual Behavior

Play once and then stops. Seems that same case as this one: https://github.com/nolimits4web/swiper/issues/7059

### Swiper version

10.3.0

### Platform/Target and Browser Versions

macOs, Chrome, Firefox, Safari ( all latest )

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Shubhamhjain** [comment] 2023-09-23 03:36
I guess i figured out the issue. Can i know where does the code for the slider exists in the codebase

**Comment by james0r** [comment] 2023-09-23 03:39
Just experienced the same. This also occurs with `pauseMouseOnEnter` for me. 

https://codesandbox.io/s/swiper-autoplay-forked-phffl2?file=/index.html:2098-2132

**Comment by kruboy14** [comment] 2023-09-25 06:20
It happens due to the following changes in the core:
> core: fix loopFix in loop and cssMode ([8180a52](https://github.com/nolimits4web/Swiper/commit/8180a52f386301147dae286994119693f6231202)), closes https://github.com/nolimits4web/Swiper/issues/6919

The previous implementation was:
`return swiper.slideTo(swiper.activeIndex + increment, speed, runCallbacks, internal);`

It has been modified to:
`return swiper.slideTo(swiper.activeIndex + increment);`

Consequently, the function no longer passes `internal` as true, causing it to halt execution at that point. [here](https://github.com/nolimits4web/swiper/blob/d8596eaa886c07f74f4fb506b38b42b6a03f8eef/src/modules/autoplay/autoplay.mjs#L264C2-L271C6)

Additionally, setting `cssMode` to true helped me to fix it

**Comment by 349989153** [comment] 2023-09-25 09:29
same problem with same 10.3.0

**Comment by Luckyfella73** [comment] 2023-09-26 09:32
I can confirm the autoplay issue using swiper 10.3.0 (importing swiper as module). Slider swipes one time and then freezes. In my case it is not working even when setting `disableOnInteraction: false`

Until this is fixed in the package we can set `cssMode: true` like @kruboy14 suggested - thanks kruboy!

**Closed** 2023-09-28 07:55 UTC
