### ISSUE TITLE
Bug in Multiple Slides Per View Demo

### ISSUE THREAD

**Issue by Craigy-** [nolimits4web/swiper#3434] opened 2020-02-05 12:03 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.0.
* Platform/Target and Browser Versions: Win10 with latest Chrome, Firefox. Also Chrome on Android.
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/110-slides-per-view.html

This configuration (in my code and in your demo) have a bug when swiper is reached the end.
Please look at this videos:
http://craigy.ru/t/swiper-issue/demo.gif
http://craigy.ru/t/swiper-issue/my.gif

**Comment by nolimits4web** [comment] 2020-02-05 12:08
Duplicate of #3398

**Closed by nolimits4web** 2020-02-05 12:08 UTC
