### ISSUE TITLE
Carousel items getting blurry after clicking prev/next arrow (Has demo)

### ISSUE THREAD

**Issue by KongCheeHong** [nolimits4web/swiper#4166] opened 2021-01-29 10:51 UTC
- Swiper Version: 6.4.9 (latest)
- Platform: Mac OS Catelina Version 10.15.6 (19G2021)
- Browser Versions: Goole Chrome Version 88.0.4324.96 (Official Build) (x86_64)

I'm facing an issue which the carousel item are getting blurry after clicking prev/next arrows. It happened where the carousel items are more than 100++, it will getting more blurry if your items are more and more.

Example/Demo: https://codepen.io/kchkch/pen/OJbJbem

**Comment by andrea3aga** [comment] 2021-02-08 20:48
Me too.
As you add new images to the carousel, the transition becomes increasingly blurred.

**Comment by opiepj** [comment] 2021-02-10 19:52
Same issue with me.  Seems to only be happening on Chrome. I used "roundLengths", but doesn't work.

**Comment by opiepj** [comment] 2021-02-10 19:55
I was able to remove the problem by adding this hack to my global styles.

```css
.swiper-slide {
  -webkit-backface-visibility: hidden;
}
```

Lame :/

**Comment by akhatri** [comment] 2021-02-20 15:17
@opiepj i had the same issue and your fix worked! Could we please get this fixed in the main version as it looks like a common issue. I had this issue with the swiper-react version too

**Comment by saiichihashimoto** [comment] 2021-03-20 05:13
👍 on the issue, 👍 on @opiepj, 😢 on @nolimits4web closing the PR without a good alternative.

**Comment by nolimits4web** [comment] 2023-10-24 12:27
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed** 2023-10-24 12:27 UTC
