### ISSUE TITLE
Svelte functionality not working in duplicated looped slides

### ISSUE THREAD

**Issue by silllli** [nolimits4web/swiper#4261] opened 2021-02-23 12:12 UTC
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: macOS 11.2.1, Chrome Version 88.0.4324.182

## What You Did

Added content to a `SwiperSlide` that uses Svelte functionality in a looped `Swiper` instance.

```
<script>
  let timesClicked = 0;
</script>

<Swiper loop={true}>
  <SwiperSlide>
    Times clicked: {timesClicked}
    <button on:click={() => timesClicked++}
  </SwiperSlide>
  <SwiperSlide><OrAnotherComponentDoingSvelteThings /></SwiperSlide>
</Swiper>
```

When going from the last slide to the first (by using the loop), that first (duplicated) slide always shows the initial state (`Times clicked: 0`) and does not update the variable when clicking the button. As soon as you move the slide a little, the non-duplicated version of it becomes visible and everything works again.

[View the problem here.](https://codesandbox.io/s/swiper-svelte-fork-forked-o2v53?file=/App.svelte)

I think this could be the same problem as in this issue with Vue #3938.

## Expected Behavior

The duplicated slides being in sync with the actual ones.

## Actual Behavior

Only the DOM elements are being duplicated without taking Svelte functionality into account.

**Comment by mrmikardo** [comment] 2021-10-04 11:44
I have also experienced this issue with components that dispatch `click` events - the events are only dispatched by the initial set of swiper slides, and not by the duplicated slides.

**Comment by starguide0** [comment] 2021-12-09 04:13
<script>
  let timesClicked = 0;
  function counter(e){
     const [swiper, touchEvent] = e.detail[0];
     let idx = (swiper.activeIndex -1) % 2;   2 is slide count
     if(!(idx % 2)) timesClicked++
  }
</script>

<Swiper loop={true}
 on:click={counter}
>
  <SwiperSlide>
    Times clicked: {timesClicked}
  </SwiperSlide>
  <SwiperSlide><OrAnotherComponentDoingSvelteThings /></SwiperSlide>
</Swiper>

**Comment by eden-omb** [comment] 2022-01-12 10:51
Confirming this is still an issue with Swiper 7.4.1. This is not a feature request, this is a bug and is currently a blocker for me. [See here](https://codesandbox.io/s/swiper-default-svelte-forked-kj1iz?file=/App.svelte-kj1iz?file=/App.svelte) for modern reproduction. Te reiterate, **Swiper loop is currently broken** using Svelte. Is there anything I can do to help here?

**Comment by nolimits4web** [comment] 2022-01-12 10:59
Due to how loop works (duplicating slides DOM elements), it is not possible to keep Svelte functionality on duplicated slides, because there is no way in Svelte (as far as I know) to duplicate passed slides/components with Svelte, like it is done in React/Vue where there is a full control on children elements/components passed to component.

There only way I currently see is to make rendering of slides similar to Virtual Slides functionality in svelte based on slides data, that is why it is marked as feature request to implement this new thing in Svelte

**Comment by eden-omb** [comment] 2022-01-12 15:36
This is still a bug even if it requires a feature to fix. The virtual slides thing should be a separate issue. This issue describes a bug that, at least to me, makes Swiper completely unusable.

This being said, I don't understand how virtual slides work in Swiper or how the duplication occurs currently, but this seems to be as simple as simply reusing the default slot in Svelte, [see my demo here](https://codesandbox.io/s/nice-einstein-pzf6k?file=/App.svelte)

**Comment by nolimits4web** [comment] 2022-01-12 15:53
Not as simple as
> but this seems to be as simple as simply reusing the default slot in Svelte

How do you transform [1,2,3,4] children to [4,1,2,3,4,1] in Svelte?

**Comment by eden-omb** [comment] 2022-01-16 10:20
Why not render all children 3 times and simply start from the middle one? It wouldn't be as performant as it otherwise could be, but it wouldn't be broken. Please explain how this performance hit in Svelte is not better than the alternative of breaking slide behavior in loop mode.

**Comment by nolimits4web** [comment] 2023-02-01 10:26
New Swiper v9 doesn't have Svelte components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.

**Closed by nolimits4web** 2023-02-01 10:26 UTC
Labels: feature request, Svelte
