### ISSUE TITLE
Swiper 6.x instance cannot be assigned to Vue data

### ISSUE THREAD

**Issue by LZQCN** [nolimits4web/swiper#3685] opened 2020-07-13 11:39 UTC
* [x] bug

* Swiper Version: 6.0.2
* Platform/Target and Browser Versions: Chrome 83.0.4103.116

### What you did
Normal operation：
```
<template>
  <div class="home">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</template>

<script>
import Swiper, { Pagination, Autoplay } from 'swiper';

Swiper.use([Pagination, Autoplay]);

let swiper = null;
export default {
  name: 'Home',
  mounted() {
    swiper = new Swiper('.swiper-container', {
      autoplay: {
        delay: 3000,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
  },
  destroyed() {
    swiper.destroy();
  },
};
</script>
```

Throw an error：
```
<template>
  <div class="home">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</template>

<script>
import Swiper, { Pagination, Autoplay } from 'swiper';

Swiper.use([Pagination, Autoplay]);

export default {
  name: 'Home',
  data() {
    return {
      swiper: null, // Code changes
    };
  },
  mounted() {
    this.swiper = new Swiper('.swiper-container', {
      autoplay: {
        delay: 3000,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
  },
  destroyed() {
    this.swiper.destroy();
  },
};
</script>

<style lang="scss" src="@/assets/swiper.scss"></style>
<style lang="scss" scoped>
.swiper-container {
  width: 600px;
  height: 300px;
}
</style>
```
```
swiper.esm.js?192f:242 Uncaught TypeError: $el.css is not a function
    at Swiper.updateSize (swiper.esm.js?192f:242)
    at Swiper.onTouchStart (swiper.esm.js?192f:1925)
updateSize @ swiper.esm.js?192f:242
onTouchStart @ swiper.esm.js?192f:1925
17swiper.esm.js?192f:1105 Uncaught TypeError: swiper.$wrapperEl.transition is not a function
    at Swiper.setTransition (swiper.esm.js?192f:1105)
    at Swiper.onTouchMove (swiper.esm.js?192f:2074)
```
I guess this may be an Object.defineProperty conflict between Vue and Swiper

**Comment by usb248** [comment] 2020-07-13 17:15
duplicate of : https://github.com/nolimits4web/swiper/issues/3671

**Comment by nolimits4web** [comment] 2020-07-14 15:13
Duplicate of #3671

**Closed by nolimits4web** 2020-07-14 15:13 UTC
