### ISSUE TITLE
Modules in CSS instead of SCSS

### ISSUE THREAD

**Issue by bramvdpluijm** [nolimits4web/swiper#4056] opened 2020-12-17 10:50 UTC
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 6.4.1.
* Platform/Target and Browser Versions: N/A.
* Live Link or JSFiddle/Codepen or website with isssue: N/A.

### What you did
Tried to import scss inside a Next.js component, but current setup does not use sass and Swiper does not include css files for it's modules. Only scss and less.

### Expected Behavior
It would be nice if the separate Swiper modules, like the Navigation, Pagination etc. would also have compiled css styles instead of only scss and less. That way Swiper will be supported on Next.js without further customization or the need to install sass only for this specific library. Why is swiper/swiper-bundle compiled to css and all other modules in scss?

### Actual Behavior
Not able to use specific module styling for Pagination and Navigation as there's only scss and less files available.

**Comment by nolimits4web** [comment] 2020-12-17 11:00
Duplicate of #4053

**Closed by nolimits4web** 2020-12-17 11:00 UTC
