### ISSUE TITLE
Swiper "jump" strange behavior

### ISSUE THREAD

**Issue by davide93** [nolimits4web/swiper#6710] opened 2023-05-25 13:59 UTC
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/upydavide/pen/dygrVbv

### Bug description

When within the swiper-slide I try to open a modal when I close it swiper sets the slide containing the previousvly clicked button as the active slide and "jump" to it.

No problem up to v. 7.41 - issue in Swiper 8 and 9

### Actual Behavior

Codepen: open the modal with the button placed inside swiper, then try to close the modal.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by straycoders** [comment] 2023-06-05 23:24
Hi @davide93, I'm also using version 9.3.2 and was able  to solve this (hopefully). What I did was, commenting out the line number 6929 in the source file `swiper-bundle.js` where mentioned
`swiper.slideTo(swiper.slides.indexOf(slideEl), 0)`

To be clear, find this block:
```
const handleFocus = e => {
   if (swiper.a11y.clicked) return;
   const slideEl = e.target.closest(`.${swiper.params.slideClass}, swiper-slide`);
   if (!slideEl || !swiper.slides.includes(slideEl)) return;
   const isActive = swiper.slides.indexOf(slideEl) === swiper.activeIndex;
   const isVisible = swiper.params.watchSlidesProgress && swiper.visibleSlides && swiper.visibleSlides.includes(slideEl);
   if (isActive || isVisible) return;
   if (e.sourceCapabilities && e.sourceCapabilities.firesTouchEvents) return;
   if (swiper.isHorizontal()) {
     swiper.el.scrollLeft = 0;
   } else {
     swiper.el.scrollTop = 0;
   }
   //swiper.slideTo(swiper.slides.indexOf(slideEl), 0);
 };

```
Well, so far so good. HTH.

**Comment by davide93** [comment] 2023-06-12 09:39
This seems to solve the problem, thank you @straycoders 

@nolimits4web would it be possible to have it in the next release?

Thank you

**Comment by alexarnaud** [comment] 2023-07-10 14:13
Hello,

What goal are you trying to achieve exactly?

The behavior I saw is you click on the button to open the modal then you close the modal then the focus is on the button to open the modal again.  This behavior is the proper one.

This behavior you dislike is the only one to ensure your website meets Web Contents Accessibility Guidelines. If the focus is not set after closing the modal, it means for some screen reader users like me that the focus will be back at the top of the page, which is very inconvenient.

For the reminder, 15% of the population has a disability, so excluding 15% of the population is probably not the way to go

**Comment by davide93** [comment] 2023-08-25 09:05
@alexarnaud 
For me the right behavior should be that if the slide with the clicked button is totally on the right side of the screen when clicked, when the modal is closed this slide remains on the right side and not moved totally to the left side.

**Comment by davide93** [comment] 2023-08-25 09:13
However, `watchSlidesProgress: true` parameter solves the problem.

@straycoders thanks anyway for the suggested quick workaround.

**Comment by nolimits4web** [comment] 2023-10-24 12:53
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Closed by nolimits4web** 2023-10-24 12:53 UTC
