### ISSUE TITLE
console errors using breakpoints

### ISSUE THREAD

**Issue by marcomarasco** [nolimits4web/Swiper#1511] opened 2015-11-23 22:38 UTC
i have an issue using breakpoints. when i define some breakpoints for a carousel i get this errors in console:
```javascript
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    .scrollbar.set @ swiper.js:2555
    .onResize @ swiper.js:999
```

i have also notice that console errors are shown in reference to the largest size specified for the breakpoints.

for example if i set two breakpoint one `320px` and another one at `550px`, console error shows up:
- when i open the page with screen size 900px;
- when i open the page with a screen size of 400px and resize window to overcome 550px.

same issue with swiper.jquery version with the following error

```javascript
Uncaught TypeError: Cannot read property 'createDocumentFragment' of undefined
    n.extend.buildFragment @ jquery.js:5087
    n.fn.extend.domManip @ jquery.js:5387
    n.fn.extend.append @ jquery.js:5218
    s.scrollbar.set @ swiper.jquery.js?ver=3.2.0:2561
    s.onResize @ swiper.jquery.js?ver=3.2.0:1009
```

how i can prevent or fix this issue?

**Comment by nolimits4web** [comment] 2015-11-25 10:59
Would be good to see live example or JSFiddle with this issue

**Comment by puredazzle** [comment] 2015-11-25 15:38
I have the same error, when I add breakpoints I get the following error:
`Uncaught TypeError: Illegal invocation`

This is my code:

```
import Swiper from 'swiper';
import {mqXs, mqSm} from '../lib/media-queries';

export default class NewArrivals {
  constructor() {
    this.slideshow = null;
    this.wrapper = document.getElementById('new-arrivals');
  }

  load() {
    if (!this.wrapper) {
      return;
    }

    const slider = this.wrapper.querySelector('.swiper-container');
    const nextButton = this.wrapper.querySelector('.next-slide-button');
    const prevButton = this.wrapper.querySelector('.prev-slide-button');

    if (slider) {
      this.slideshow = new Swiper(slider, {
        speed: 400,
        loop: false,
        slidesPerView: 3,

        nextButton: nextButton,
        prevButton: prevButton,

        breakpoints: {
          [mqXs]: {
            slidesPerView: 1
          },
          [mqSm]: {
            slidesPerView: 1
          }
        }
      });
    }
  }
}
```

**Comment by nolimits4web** [comment] 2015-11-25 15:41
@puredazzle is this JavaScript? What does this syntax mean?
```
[mqXs]: {
            slidesPerView: 1
          },
```

**Comment by puredazzle** [comment] 2015-11-25 15:46
@nolimits4web I have the media queries saved in a separate file, which I require in the top of my slider.js. It is es6 code.

This is how my media-queries looks like:
```
export const mqXs = 480;
export const mqSm = 768;
export const mqMd = 992;
export const mqLg = 1200;
```

**Comment by nolimits4web** [comment] 2015-11-25 15:49
Ok, but you can't define Object keys like that. If they are dynamic, then it should be something like:
```
var swiperParams = {
    speed: 400,
    loop: false,
    slidesPerView: 3,

    nextButton: nextButton,
    prevButton: prevButton,
    breakpoints: {}
}
swiperParams[mqXs] = {
    slidesPerView: 1
};

this.slideshow = new Swiper(slider, swiperParams);
...

**Comment by puredazzle** [comment] 2015-11-25 15:51
I get the same error if I use:
```
      this.slideshow = new Swiper(slider, {
        speed: 400,
        loop: false,
        slidesPerView: 3,

        nextButton: nextButton,
        prevButton: prevButton,

        breakpoints: {
          480: {
            slidesPerView: 1
          }
        }
      });
```

If it loads and the screen is less then 480px it works, but if it loads and the screen is bigger it fails.

**Comment by nolimits4web** [comment] 2015-11-25 15:58
Then problem somewhere else, as you can see there is no such problem at http://www.idangero.us/swiper/demos/33-responsive-breakpoints.html Would be good to see live example

**Comment by puredazzle** [comment] 2015-11-25 16:09
I will try to upload a live example. It seems like the error first triggers in `Dom7.on`. But will upload a live example so it is easier to test and see.

**Comment by quintenvk** [comment] 2015-12-01 12:42
I can confirm this is an issue, too. It specifically occurs when you pass a **DOM-node** as the next and/or prev button; when you pass a selector, all is well. This is problematic because you need to pass a DOM node if you have multiple swiper instances on the page. [fiddle to play with](http://jsfiddle.net/XMV2r/102/).

Comment/uncomment the current next-prev button config parameters. The problem seems to be an object that's being passed to jQuery instead of a DOMnode by the swiper, causing the browser to throw an error because jQuery in turn tries to map an event to this object.

**Comment by nolimits4web** [comment] 2015-12-01 15:04
@quintenvk thanks for the fiddle, now it is fixed in dev

**Closed by nolimits4web** 2015-12-01 15:04 UTC

**Comment by 91Abdullah** [comment] 2015-12-28 10:50
Now, it is throwing error: Uncaught TypeError: Cannot read property 'nodeType' of null

**Comment by 91Abdullah** [comment] 2015-12-28 11:02
Actually, its working fine. It was confused with selector I used ID instead of class and it worked like a charm!
